### ISSUE TITLE
Price change percentage on two lines when price are going down more than 10%

### ISSUE THREAD

**Issue by ronnyandre** [conorwalsh/esp8266-crypto#1]
Now that the market is going way down, the price change in percentage is above 10 % negative, this renders the percentage sign on the next line, overlaying the crypto logo.

Took some photos, the first one is correct (sorry about the lines on the OLED, difficult to time):

![IMG_5480](https://user-images.githubusercontent.com/68879/108840116-2f2f1d00-75d6-11eb-8b47-69b2f760fd43.jpg)

And here's one where the percentage sign is on the next line:

![IMG_5481](https://user-images.githubusercontent.com/68879/108840147-37875800-75d6-11eb-8ea9-8de23228f512.jpg)

**Comment by conorwalsh** [comment]
Thanks for reporting this issue my guess is that the print function doesn't work exactly how I thought it did!
On line 372:
`display.print(change,0);`
should probably change to
`display.print((int)change);`
I will validate this change and update the code with a solution soon.

**Comment by conorwalsh** [comment]
Fixed, the check only worked for when prices increased by 10% not decreased by 10% `abs` to get the absolute value fixed it
