### ISSUE TITLE
Price number format

### ISSUE THREAD

**Issue by PauliusBaronas** [conorwalsh/esp8266-crypto#7]
Hello, how to make the price number format exclude the letter " E " ? I would like to have a normal rounded number of lets say 5 digits.

**Comment by conorwalsh** [comment]
This can be done within this snippet:
```
char priceBuf[20];
// Get correct currency symbol
char currencySymbol = '$';
if(assets[currentAsset].isCrypto)
  currencySymbol = CURRENCY_SYM;
// Construct the price string
if(price<10){
  sprintf(priceBuf, "%c%.5f", currencySymbol, price);
}
else {
  sprintf(priceBuf, "%c%.3f", currencySymbol, price);
}
```
Found here: https://github.com/conorwalsh/esp8266-crypto/blob/main/esp8266-crypto.ino#L486

Just remove the `%c` and `currencySymbol` from the `sprintf`
