### ISSUE TITLE
finnhub code portion not active

### ISSUE THREAD

**Issue by netjlee** [conorwalsh/esp8266-crypto#8]
Hi ,
Need help with Finnhub portion of code. Everything works and compiles and my arduino shows crypto stocks
perfectly but does not advance past the crypto coins. Another words it wont post or show the stocks even though I generated an api key, Adjusted the true/false tag and it still doesn't show those stocks. Is there and additional step I'm missing to get stocks to show?
![image](https://user-images.githubusercontent.com/93002966/147865040-14dcb327-4c44-4585-86d4-edff9eb6fdb7.png)
vs
![image](https://user-images.githubusercontent.com/93002966/147865050-51b4cb31-eb1b-4be4-9ab0-d64be46d5924.png)

Any help appreciated. Thanks!

**Comment by conorwalsh** [comment]
Does the standard code with your API key work as provided? I would start there.
The true/false value tells the program if the asset is a crypto (true) or a stock (false), so it must be false for finnhub.
I haven't run this project in a while and don't currently have the HW to run it ATM

**Comment by netjlee** [comment]
Thank you for replying, you indirectly solved it. I assumed your flags were "on or off" instead of true or false ;) That corrected it!!

QQ, is there code that can be run from a pc or mac that you are aware of that can easily update the api key and or the wifi settings? This would be really handy to know. Thank you again!!

**Comment by conorwalsh** [comment]
No problem!
I can see how that could be confusing, I just updated the code to use ``CRYPTO`` and ``STOCK`` flags instead of ``true`` and ``false``.
I dont think so you will have to re-flash the ESP when those values change.

**Comment by netjlee** [comment]
ok, no worries, I will also update my code to reflect the crypto/stock adjustment. ;)
